sun = false
moon = false
stars = false

iris.features.optional=ENTITY_TRANSLUCENT

screen.columns = 2
screen = RENDER_CLOUDS ARMOR_COLOR_MODE SKIN_LAYER1_MODE SKIN_LAYER2_MODE SKIN_LAYER2_INVERT SKIN_LAYER2_SQUARE_TEXTURE_FALLBACK SKIN_LAYER2_DEBUG
